## 4.1 Numpy

In [1]:
import numpy as np

In [2]:
# １次元配列
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape #１次元配列で３要素

(3,)

In [7]:
#　２次元配列
b =np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

### 変形

In [10]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [11]:
c1.shape

(6,)

In [12]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
#　要素数が合わないとエラー
#c3 = c1.reshape((3,4))

In [14]:
# ravelで元に戻す
c3 = c2.ravel() # 参照を返す⇄copy
c3

array([0, 1, 2, 3, 4, 5])

In [15]:
c4 = c2.flatten() # copy を返す
c4

array([0, 1, 2, 3, 4, 5])

### データ型

In [16]:
a.dtype

dtype('int64')

In [17]:
d = np.array([1, 2], dtype = np.int16)
d

array([1, 2], dtype=int16)

In [18]:
d.dtype

dtype('int16')

In [19]:
d.astype(np.float16) # astype:データ型変換

array([1., 2.], dtype=float16)

### インデックスとスライス

In [20]:
a

array([1, 2, 3])

In [21]:
a[0]

1

In [22]:
a[1:]

array([2, 3])

In [23]:
a[-1]

3

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b[0] # １行目の取得

array([1, 2, 3])

In [26]:
b[1, 0] #２行目の1列目の値

4

In [27]:
b[:, 2] # 全ての行の3列目の値

array([3, 6])

In [28]:
b[1, :]

array([4, 5, 6])

In [29]:
b[0, 1:]

array([2, 3])

In [30]:
b[:, [0, 2]]  #インデックス値が飛んでいる場合の取得方法　全ての行に対して0番目と2番目の２列を取得

array([[1, 3],
       [4, 6]])

### データ改変

In [31]:
a

array([1, 2, 3])

In [32]:
a[2] = 4
a

array([1, 2, 4])

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [35]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

### 深いコピー

In [36]:
a1 = a
a1

array([1, 2, 4])

In [37]:
a1[1] = 5
a1

array([1, 5, 4])

In [38]:
a

array([1, 5, 4])

In [39]:
# aは書き換えをしていないが、a1 = a という操作で　a1を変更するとその参照先であるaも変更される

In [40]:
a2 = a.copy()
a2

array([1, 5, 4])

In [41]:
a2[0] = 6
a2

array([6, 5, 4])

In [42]:
a # copyの場合は元のまま

array([1, 5, 4])

In [43]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [45]:
c3

array([6, 1, 2, 3, 4, 5])

In [46]:
c4

array([0, 7, 2, 3, 4, 5])

In [47]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [48]:
#c3の書き換えの影響はあるが、c4の影響はない　⇨　ravel>参照　flatten>コピー

In [49]:
# python標準のリストではスライスされた結果はコピーが渡されるが、Numpyでは参照が渡される　　
# 渡されるものが違うので注意が必要

In [50]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2) 

[0, 1]
[2, 1]


In [51]:
# コピーが渡されるている

In [52]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [53]:
# 参照が渡されている

In [54]:
# 参照：浅いコピー　　　　　それ以外の場合：深いコピー  と呼ぶこともある

### 数列を返す(arange)

In [55]:
np.arange(10) # numpy配列が生成される　= python標準のrange関数

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
np.arange(1, 11, 2) #2つ飛ばし

array([1, 3, 5, 7, 9])

### 乱数

In [58]:
f = np.random.random((3, 2)) # np.random.random 行と列のタプルを渡すと0~1未満の乱数を生成
f

array([[0.75383749, 0.03814165],
       [0.92097562, 0.15077369],
       [0.4199115 , 0.68489988]])

In [59]:
np.random.seed(123) # 乱数のシード値を固定
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [60]:
np.random.seed(123)
np.random.rand(4,2) # np.random.rand  行と列のタプルではなく、2つの引数で形状を渡す　出している数字はrandom.randomと同じ

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [61]:
np.random.seed(123)
np.random.randint(1, 10) # 1~10未満の中から任意の整数を生成する

3

In [62]:
np.random.seed(123)
np.random.randint(1, 10, (3, 3)) #第３引数で行列を作ることも可能

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [63]:
np.random.randint(1, 10, 3) #第３引数で生成する整数の数のを指定

array([1, 1, 4])

In [64]:
np.random.seed(123)
np.random.uniform(0.0, 5.0, size = (2, 3)) # 第1引数以上かつ第２引数未満のランダムな小数値をタプルで渡した行列で生成　
#※第１引数と第２引数は省略可能 その場合は0.0、1.0がそれぞれデフォルトで指定される

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [65]:
# sizeは省略可能
np.random.seed(123)
np.random.uniform(0.0, 5.0, (2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [156]:
np.random.seed(123)
np.random.uniform(size=(4,3)) # 第１、第２引数が指定されていないので０以上１未満で生成

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [67]:
# 上記のように前の引数を省略する場合は、sizeを入れておかないと正しく行列が表示されない
np.random.seed(123)
np.random.uniform((4,3))

array([1.91059244, 2.42772133])

In [68]:
#上記は全て一様乱数だが、正規分布に従った乱数を出力する場合は、　np.random.randonを使う  ※np.random.rand に　nをつける
np.random.seed(123)
np.random.randn(4, 2) #平均0、分散1の分布で出力される

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

### 同じ要素の数列を作る

In [69]:
np.zeros(3)

array([0., 0., 0.])

In [70]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones(2)

array([1., 1.])

In [72]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 単位行列

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(1)

array([[1.]])

In [75]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### 指定値で埋める

In [76]:
np.full(3, 3.14) #3.14を3つの要素の配列にいれる

array([3.14, 3.14, 3.14])

In [77]:
np.full((2, 4), np.pi) #np.pi = 3.14（numpyの定数値）

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [78]:
np.nan

nan

In [79]:
# numpyの欠損値の穴埋めなどに使われる　float型

In [80]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

### 範囲指定で均等割データを作る

In [81]:
np.linspace(0, 1, 5) #0~1を等間隔に区切った5つの要素の配列を作る(この場合は第２引数は○未満にはならない)　＝np.arange(0.0, 1.1, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [82]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### 要素間の差分

In [83]:
l= np.array([2, 2, 6, 1, 3])

In [84]:
np.diff(l)

array([ 0,  4, -5,  2])

### 連結

In [85]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [86]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [87]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [88]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [89]:
np.concatenate([b, b1], axis = 1) # 列方向（カラム）を増やすのでaxis =1 と指定

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [90]:
#hstack関数でも同じ効果
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [91]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [92]:
# vstackは行方向に増やす
b3 = np.vstack([b, b2]) 
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割

In [93]:
first, second = np.hsplit(b3, [2]) # hsplitは列方向に分割　h(holizontal)は列、v(vertical)は行
# [2]は1つ目の配列が２列となる、という意味

In [94]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [95]:
second

array([[ 8],
       [ 8],
       [45]])

In [96]:
# vsplit で　行方向に分割
first1, second1 = np.vsplit(b3, [2])

In [97]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [98]:
second1

array([[30, 60, 45]])

### 転置

In [99]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [100]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

### 次元追加

In [101]:
a #1次元配列

array([1, 5, 4])

In [102]:
a[np.newaxis, :] # 次元追加 行方向
a

array([1, 5, 4])

In [103]:
a[:, np.newaxis] #次元追加　列方向

array([[1],
       [5],
       [4]])

### グリッドデータの生成

In [104]:
# meshgrid x座標、y座標の配列からそれらを組み合わせてできる全ての点の座標データを生成する

In [105]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [106]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [107]:
xx, yy = np.meshgrid(m, n) # mとnを行方向と列方向にグリッドデータを生成する
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [108]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

## 4.1.3  Numpyの各機能

In [109]:
import numpy as np

a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)
print('e:', e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [110]:
print('a:', a.shape)
print('b:', b.shape)
print('c:', c.shape)
print('d:', d.shape)
print('e:', e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


### ユニバーサルファンクション

In [111]:
# 配列要素内のデータ一括変換　　

# ＜絶対値を出力＞
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [112]:
np.sin(e) #sin関数

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [113]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [114]:
np.log(a)

/Users/Moriya/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [115]:
# -infは−無限大　　　log(x)はx＞０の時のみ定義されているから

In [116]:
np.log10(c) # 常用対数（logの底が10の時）

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [117]:
np.exp(a) #自然対数の底e

array([1.        , 2.71828183, 7.3890561 ])

### ブロードキャスト

In [118]:
# 配列の内部データに直接演算を行うことができる

In [119]:
a

array([0, 1, 2])

In [120]:
a + 10

array([10, 11, 12])

In [121]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [122]:
a + b # 次元が違うデータでも演算ができる

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [123]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [124]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [125]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
c - np.mean(c) # c　全部の要素の平均　21/6=3.5

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [127]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [128]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [129]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [130]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [131]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [132]:
c / a

/Users/Moriya/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [133]:
# 要素に0を含む割り算を実行すると無限大を意味するinf（とRuntime Warning)が表示される

In [134]:
c / (a + 1e-6) # infを避けるために10のマイナス６乗という非常に小さな数値を配列に加える

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

### ドット積

In [158]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)
print('e:', e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [135]:
np.dot(b, a)

array([-4,  5])

In [136]:
# ドット積　通常の行列計算（？）　配列の形状が重要　2*3行列✖️3*2行列のように内積の数字が同じ配列同士でないと計算できない　　

In [137]:
b @ a

array([-4,  5])

In [138]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [139]:
 d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### 判定・論理値

In [159]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)
print('e:', e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [140]:
a > 1

array([False, False,  True])

In [141]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [142]:
np.count_nonzero(b > 0) # nonzeroは0でない要素を出力　＋　pythonではFalseを０として扱う　→　Trueの数である２が出力

2

In [143]:
# 上記と同じ結果
np.sum(b > 0) # Trueは１と扱われるので、要素を全部足すsumで同じ結果が得られる

2

In [144]:
np.any(b > 0) # np. any →　要素の中にTrueが含まれているかどうかを判定

True

In [145]:
np.all(b > 0) # 全ての要素がTrueかどうかの判定

False

In [146]:
b[b > 0] # 条件に合致したものだけの要素を新たな配列として出力

array([1, 2])

In [147]:
b == c #同じ形状の配列の要素同士の比較

array([[False, False, False],
       [False, False, False]])

In [148]:
a == b # 一次配列と二次配列の比較　　→ブロードキャストのルールで比較される　aとbの1行目、2行目をそれぞれ比較

array([[False, False, False],
       [ True,  True,  True]])

In [149]:
(b == c) | (a == b)  #比較したもの同士のor

array([[False, False, False],
       [ True,  True,  True]])

In [150]:
b[(b == c) | (a ==b)]

array([0, 1, 2])

In [151]:
np.allclose(b, c) # 配列同士が同じ要素で構成されるかを確認

False

In [152]:
np.allclose(b, c, atol = 10) # 絶対誤差をatolで指定して、その範囲内に含まれるかを確認

True

In [153]:
# この誤差は浮動小数点計算の誤差などを無視したいときに便利な機能となる

### 関数とメソッド

In [154]:
np.sum(a) # numpy関数による表現

3

In [155]:
a.sum() #配列のメソッドでの実行

3